# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 8 * * *"
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: jonathann1203/ipv64_client_dockercontainer:v1
    steps:

      - name: "check is MY_SECRET exists"
        env: 
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN2  }}
        if: ${{ env.DOCKERHUB_TOKEN == '' }}
        run: 'echo "echo the secret \"MY_SECRET\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"'
      - name: Check pip version
        run: pip3 --version
